name: Integration
on:
  pull_request:
    branches:
    - master
    - release-*
  push:
    branches:
    - master
    - release-*
jobs:
  test-integration:
    name: Integration tests
    runs-on: [ubuntu-18.04]
    if: "!contains(github.event.head_commit.message, 'skip-actions')"
    steps:
    # - name: Skip based on commit message
    #   uses: veggiemonk/skip-commit@1.0.0
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Run integration tests
      run: make docker-test-integration
